// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251231174052_AddSessionAndScene")]
    partial class AddSessionAndScene
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastSessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSessionId")
                        .IsUnique();

                    b.HasIndex("GameSystemId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterCreationGuide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterSheetSchema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GameSystems", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RulebookChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("SummaryEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<Vector>("SummaryEmbeddingVector")
                        .HasColumnType("vector")
                        .HasColumnName("SummaryEmbedding");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("SummaryEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SummaryEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SummaryEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("RulebookChapters", null, t =>
                        {
                            t.Property("SummaryEmbedding")
                                .HasColumnName("SummaryEmbedding1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Vector>("SummaryEmbedding")
                        .HasColumnType("vector(1024)");

                    b.Property<Vector>("SummaryEmbeddingVector")
                        .HasColumnType("vector")
                        .HasColumnName("SummaryEmbedding");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SummaryEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SummaryEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SummaryEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("Scenes", null, t =>
                        {
                            t.Property("SummaryEmbedding")
                                .HasColumnName("SummaryEmbedding1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Vector>("SummaryEmbedding")
                        .HasColumnType("vector(1024)");

                    b.Property<Vector>("SummaryEmbeddingVector")
                        .HasColumnType("vector")
                        .HasColumnName("SummaryEmbedding");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CurrentSceneId")
                        .IsUnique();

                    b.HasIndex("SummaryEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SummaryEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SummaryEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("Sessions", null, t =>
                        {
                            t.Property("SummaryEmbedding")
                                .HasColumnName("SummaryEmbedding1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Domain.Entities.Session", "CurrentSession")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Campaign", "CurrentSessionId");

                    b.HasOne("Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Campaigns")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany("Campaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentSession");

                    b.Navigation("GameSystem");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.HasOne("Domain.Entities.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Domain.Entities.RulebookChapter", b =>
                {
                    b.HasOne("Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Chapters")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("Domain.Entities.Scene", b =>
                {
                    b.HasOne("Domain.Entities.Session", "Session")
                        .WithMany("Scenes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.HasOne("Domain.Entities.Campaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Scene", "CurrentScene")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Session", "CurrentSceneId");

                    b.Navigation("Campaign");

                    b.Navigation("CurrentScene");
                });

            modelBuilder.Entity("Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.GameSystem", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
